#!/usr/bin/env python3
# This script was generated by Claude Opus 5.
"""Generate demo SQL, overwriting seed_large.sql beside this script."""

import random
from datetime import datetime, timedelta
from pathlib import Path

random.seed(42)
OUT = Path(__file__).with_name("seed_large.sql")

START = datetime(2026, 4, 13, 8, 0)
END = datetime(2026, 7, 18, 23, 59)

FIRST = ["Anna", "Ben", "Clara", "David", "Emma", "Felix", "Greta", "Hannes", "Ida", "Jonas",
         "Katja", "Leon", "Mara", "Nils", "Ole", "Paula", "Quirin", "Rosa", "Sven", "Tessa",
         "Uwe", "Vera", "Wim", "Xenia", "Yannik", "Zoe", "Amir", "Leyla", "Marek", "Sofia"]
LAST = ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker",
        "Schulz", "Hoffmann", "Koch", "Richter", "Klein", "Wolf", "Neumann"]

COURSES = [
    ("Datenbanksysteme I", 40, ["Einführung", "Relationales Modell", "SQL", "Normalisierung"]),
    ("Algorithmen und Datenstrukturen", 60, ["Einführung", "Sortieren", "Graphen", "Dynamische Programmierung"]),
    ("Einführung in die Programmierung", 35, ["Einführung", "Kontrollfluss", "Funktionen", "Objekte"]),
]

# (body, [(option, fraction)]) for the first course; the others get generic questions.
DBS_QUESTIONS = [
    ("Was ist ein Primärschlüssel?", [
        ("Ein Attribut oder eine Attributmenge, die jedes Tupel eindeutig identifiziert", 1.0),
        ("Ein Attribut, das auf eine andere Relation verweist", 0.0),
        ("Das erste Attribut einer Relation", 0.0),
        ("Ein Attribut, das keine NULL-Werte enthalten darf", 0.0)]),
    ("Welche Normalform verbietet transitive Abhängigkeiten von Nicht-Schlüsselattributen?", [
        ("3NF", 1.0), ("1NF", 0.0), ("2NF", 0.0), ("BCNF", 0.5)]),
    ("Was liefert ein LEFT JOIN, wenn es keinen passenden Partner gibt?", [
        ("Die linke Zeile mit NULL-Werten für die rechte Seite", 1.0),
        ("Keine Zeile", 0.0), ("Die rechte Zeile mit NULL-Werten", 0.0), ("Einen Fehler", 0.0)]),
    ("Welche Eigenschaften gehören zu ACID? (mehrere richtig)", [
        ("Atomicity", 0.5), ("Isolation", 0.5), ("Availability", 0.0), ("Idempotency", 0.0)]),
    ("Was bewirkt GROUP BY?", [
        ("Fasst Zeilen mit gleichen Werten zu Gruppen für Aggregatfunktionen zusammen", 1.0),
        ("Sortiert das Ergebnis", 0.0), ("Entfernt Duplikate", 0.0), ("Verbindet zwei Tabellen", 0.0)]),
    ("Welche Aussagen über Fremdschlüssel sind korrekt? (mehrere richtig)", [
        ("Sie referenzieren einen Kandidatenschlüssel einer Relation", 0.5),
        ("Sie dürfen NULL sein, sofern nicht NOT NULL deklariert", 0.5),
        ("Sie müssen eindeutig sein", 0.0), ("Sie werden automatisch indiziert", 0.0)]),
    ("Was ist eine funktionale Abhängigkeit X → Y?", [
        ("Gleiche X-Werte implizieren gleiche Y-Werte", 1.0),
        ("Y ist ein Fremdschlüssel auf X", 0.0), ("X und Y sind Kandidatenschlüssel", 0.0),
        ("Y kann aus X berechnet werden", 0.0)]),
    ("Wann ist eine Relation in BCNF?", [
        ("Wenn jede Determinante ein Superschlüssel ist", 1.0),
        ("Wenn sie keine mehrwertigen Attribute hat", 0.0),
        ("Wenn sie genau einen Kandidatenschlüssel hat", 0.0),
        ("Wenn alle Attribute prim sind", 0.0)]),
    ("Was unterscheidet eine View von einer Tabelle?", [
        ("Eine View speichert keine Daten, sondern eine gespeicherte Anfrage", 1.0),
        ("Eine View kann nicht abgefragt werden", 0.0), ("Eine View hat keinen Namen", 0.0),
        ("Eine View ist immer materialisiert", 0.0)]),
    ("Wozu dient ein Index?", [
        ("Beschleunigt die Suche nach Werten einer Spalte", 1.0),
        ("Erzwingt referenzielle Integrität", 0.0), ("Sortiert die Tabelle physisch", 0.5),
        ("Reduziert den Speicherbedarf", 0.0)]),
]

TOPICS = ["Frage zu Übungsblatt", "Klausurvorbereitung", "Literaturempfehlung", "Fehler in den Folien",
          "Termin der Sprechstunde", "Gruppensuche", "Installationsprobleme", "Verständnisfrage Vorlesung",
          "Abgabeformat", "Nachbesprechung", "Zusatzmaterial", "Hinweis zur Bewertung"]
BODIES = ["Kann das jemand kurz erklären?", "Danke, das hat geholfen.", "Ich habe dasselbe Problem.",
          "Siehe Folie 12, dort steht es.", "Wird in der Übung besprochen.", "Gibt es dazu eine Quelle?",
          "Ist inzwischen korrigiert.", "Bitte per Mail an mich.", "Funktioniert bei mir auch nicht.",
          "Das steht so in der Aufgabenstellung."]
FEEDBACK = ["Gut gelöst.", "Kleinere Fehler bei den Details.", "Sehr sauber.", "Bitte Begründung ergänzen.",
            "Aufgabe 3 fehlt.", "Vollständig und korrekt.", "Notation uneinheitlich.", "Ausgezeichnet."]
GRADING_METHODS = ["highest", "last", "average", "first"]

# One free-text question per quiz, marked by hand.
FREE_TEXT = {
    1: ["Erläutern Sie, warum eine Zerlegung verlustfrei sein muss.",
        "Wann ist eine Sicht aktualisierbar? Begründen Sie."],
    2: ["Beschreiben Sie das Vorgehen von Mergesort in eigenen Worten.",
        "Wann liefert eine Greedy-Strategie ein Optimum?"],
    3: ["Erklären Sie den Unterschied zwischen Wert- und Referenzsemantik.",
        "Wozu dient eine Schleifeninvariante?"],
}
FREE_TEXT_ANSWERS = [
    "Siehe Vorlesung, Kapitel 3; ich fasse die drei Schritte kurz zusammen.",
    "Das folgt direkt aus der Definition, weil sonst die Bedingung verletzt wäre.",
    "Ich habe den Ansatz skizziert, konnte ihn aber nicht zu Ende führen.",
    "Kurz: zuerst prüft man die Voraussetzung, dann wendet man das Verfahren an.",
    "Leider keine Zeit mehr.",
]

rows: dict[str, tuple[tuple[str, ...], list[tuple]]] = {}


def add(table, cols, *vals):
    rows.setdefault(table, (cols, []))[1].append(vals)


def uid(kind, n):
    return f"00000000-0000-0000-{kind:04d}-{n:012d}"


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, datetime):
        return f"'{v:%Y-%m-%d %H:%M:%S}'"
    if isinstance(v, list):
        return "ARRAY[" + ",".join(sql(x) for x in v) + "]"
    return "'" + str(v).replace("'", "''") + "'"


def bell(mu, sigma, lo=0.0, hi=1.0):
    return min(hi, max(lo, random.gauss(mu, sigma)))


def activity_time(lo, hi):
    """Weekday- and hour-weighted timestamp between lo and hi."""
    if hi < lo:
        raise ValueError("activity interval ends before it starts")
    while True:
        t = lo + timedelta(seconds=random.uniform(0, (hi - lo).total_seconds()))
        if random.random() > [0.9, 1.0, 1.0, 0.95, 0.7, 0.3, 0.35][t.weekday()]:
            continue
        # Reject quiet hours rather than replacing the hour, which can leave the interval.
        if random.random() < (1.0 if 9 <= t.hour <= 21 else 0.15):
            assert lo <= t <= hi
            return t


# users
PROFS = ["Prof. Maria Schmidt", "Prof. Thomas Lang", "Prof. Julia Berg"]
HIWIS = ["Lukas Brandt", "Nina Vogel"]
STUDENTS = [f"{FIRST[i]} {LAST[(i * 7) % len(LAST)]}" for i in range(30)]
users = {}
for n, name in enumerate(PROFS + HIWIS + STUDENTS, start=1):
    users[name] = uid(1, n)
    local = name.lower().replace("prof. ", "").replace(" ", ".").replace("ü", "ue").replace("ö", "oe")
    domain = "example.de" if name in PROFS else "student.example.de"
    add("\"user\"", ("uuid", "email", "username", "full_name", "password_hash"),
        users[name], f"{local}@{domain}", local.split(".")[-1] + str(n), name, f"hash{n}")

ROLES = {"Studierende": uid(2, 1), "Dozierende": uid(2, 2), "HiWi": uid(2, 3)}
for name, u in ROLES.items():
    add("role", ("uuid", "name"), u, name)
PERMS = {"quiz.create": uid(3, 1), "grade.assign": uid(3, 2), "file.upload": uid(3, 3)}
for name, u in PERMS.items():
    add("permission", ("uuid", "name"), u, name)
for role, perms in [("Dozierende", PERMS), ("HiWi", ["quiz.create", "file.upload"]), ("Studierende", ["file.upload"])]:
    for p in perms:
        add("role_permission", ("role_uuid", "permission_uuid"), ROLES[role], PERMS[p])

# courses, sections, membership, roles
enrolled: dict[int, list[str]] = {}
sections: dict[int, list[str]] = {}
groupings: dict[int, str] = {}
groups: dict[int, list[tuple[str, list[str]]]] = {}
for c, (title, cap, secs) in enumerate(COURSES, start=1):
    cu = uid(6, c)
    add("course", ("uuid", "title", "start_date", "end_date", "max_capacity", "enrollment_key"),
        cu, title, START.date().isoformat(), END.date().isoformat(), cap, f"key{c}")
    sections[c] = []
    for s, sec in enumerate(secs, start=1):
        su = uid(7, c * 100 + s)
        sections[c].append(su)
        # The last section of the first course is not released yet.
        add("course_section", ("uuid", "course_uuid", "title", "position", "visibility"),
            su, cu, sec, s, "hidden" if c == 1 and s == len(secs) else "visible")
        add("file", ("uuid", "section_uuid", "title", "type", "url"),
            uid(8, c * 100 + s), su, f"Folien {sec}", "document", f"/files/{c}/{s}/folien.pdf")
    add("file", ("uuid", "section_uuid", "title", "type", "url"),
        uid(8, c * 100 + 50), sections[c][0], "Aufzeichnung Vorlesung 1", "video", f"/files/{c}/vl01.mp4")
    add("file", ("uuid", "section_uuid", "title", "type", "url"),
        uid(8, c * 100 + 51), sections[c][0], "Vorlesungsseite", "link", f"https://example.de/kurs/{c}")
    add("hypertext", ("uuid", "section_uuid", "title", "body"),
        uid(21, c), sections[c][0], "Organisatorisches", "Übung donnerstags, Abgaben bis Sonntag 23:59.")
    members = [PROFS[c - 1], HIWIS[c % 2]] + [s for s in STUDENTS if random.random() < 0.7]
    enrolled[c] = [m for m in members if m in STUDENTS]
    for m in members:
        # A few students drop the course during the semester.
        status = "inactive" if m in STUDENTS and random.random() < 0.07 else "active"
        add("course_member", ("user_uuid", "course_uuid", "joined_at", "status"), users[m], cu,
            START - timedelta(days=random.randint(1, 14)), status)
        role = "Dozierende" if m in PROFS else "HiWi" if m in HIWIS else "Studierende"
        add("role_assignment", ("user_uuid", "role_uuid", "course_uuid"), users[m], ROLES[role], cu)
    gp = uid(23, c)
    groupings[c] = gp
    groups[c] = []
    add("grouping", ("uuid", "course_uuid", "name"), gp, cu, "Übungsgruppen")
    for g in range(3):
        gu = uid(22, c * 10 + g)
        add("course_group", ("uuid", "course_uuid", "name"), gu, cu, f"Gruppe {g + 1}")
        add("grouping_group", ("grouping_uuid", "group_uuid"), gp, gu)
        groups[c].append((gu, enrolled[c][g::3]))
        for m in enrolled[c][g::3]:
            add("group_member", ("group_uuid", "user_uuid"), gu, users[m])

# assignments, submissions, grades
task_n = sub_n = grade_n = notif_n = 0
for c in range(1, 4):
    weeks = [4, 8, 12] if c == 1 else [5, 10]
    for i, w in enumerate(weeks, start=1):
        task_n += 1
        tu, fu = uid(9, task_n), uid(10, task_n)
        due = START + timedelta(weeks=w, days=6, hours=15, minutes=59)
        add("task", ("uuid", "course_section_uuid", "name"), tu, sections[c][min(i, 3)], f"Übungsblatt {i}")
        group_mode = i == 2
        add("file_upload", ("uuid", "task_uuid", "title", "max_points", "due_date", "cut_off_date",
                            "group_mode", "grouping_uuid"),
            fu, tu, f"Abgabe Übungsblatt {i}", 10.0, due, due + timedelta(days=2),
            group_mode, groupings[c] if group_mode else None)
        # A group assignment is handed in once per group, by one of its members.
        if group_mode:
            handins = [(random.choice(ms), gu, ms) for gu, ms in groups[c] if ms]
        else:
            handins = [(m, None, [m]) for m in enrolled[c]]
        for m, gu, credited in handins:
            if random.random() > 0.85:
                continue
            late = random.random() < 0.08
            at = due + timedelta(hours=random.uniform(0.5, 30)) if late else due - timedelta(hours=168 * random.random() ** 3)
            sub_n += 1
            add("submission", ("uuid", "file_upload_uuid", "submitter_uuid", "group_uuid", "file_refs", "submitted_at"),
                uid(11, sub_n), fu, users[m], gu, [f"/submissions/{sub_n}.pdf"], at)
            if random.random() < (0.95 if due < datetime(2026, 7, 1) else 0.4):
                grade_n += 1
                points = round(10 * bell(0.72, 0.18) * 2) / 2
                graded = at + timedelta(days=random.randint(3, 10), hours=random.randint(8, 18))
                add("grade", ("uuid", "grader_uuid", "submission_uuid", "attempt_uuid",
                              "question_uuid", "points", "feedback", "graded_at"),
                    uid(12, grade_n), users[random.choice([PROFS[c - 1], HIWIS[c % 2]])], uid(11, sub_n),
                    None, None, points, random.choice(FEEDBACK), graded)
                for r in credited:
                    notif_n += 1
                    add("notification", ("uuid", "recipient_uuid", "type", "payload", "created_at", "read_at"),
                        uid(19, notif_n), users[r], "grade", f'{{"submission_uuid": "{uid(11, sub_n)}", "points": {points}}}',
                        graded, graded + timedelta(hours=random.randint(1, 72)) if random.random() < 0.7 else None)

# question bank, quizzes, attempts
q_n = opt_n = quiz_n = att_n = 0
questions: dict[int, list[tuple[str, list[tuple[str, float]], float, int]]] = {}
free_text: dict[int, list[str]] = {}
for c in range(1, 4):
    questions[c] = []
    free_text[c] = []
    bank = DBS_QUESTIONS
    if c != 1:
        bank = []
        for k in range(1, 11):
            fr = [1.0, 0.0, 0.0, 0.0]
            random.shuffle(fr)
            bank.append((f"Frage {k} zu {COURSES[c - 1][2][1 + k % 3]}", [(f"Antwort {l}", f) for l, f in zip("ABCD", fr)]))
    for body, opts in bank:
        q_n += 1
        qu = uid(13, q_n)
        add("question", ("uuid", "course_uuid", "body", "type", "default_points"), qu, uid(6, c), body, "mcq", 2.5)
        ous = []
        for pos, (text, fraction) in enumerate(opts, start=1):
            opt_n += 1
            ous.append((uid(14, opt_n), fraction))
            add("question_option", ("uuid", "question_uuid", "position", "body", "fraction"), uid(14, opt_n), qu, pos, text, fraction)
        wrong = [i for i, (_, f) in enumerate(ous) if f == 0]
        questions[c].append((qu, ous, random.uniform(0.35, 0.9), random.choice(wrong)))
    for body in FREE_TEXT[c]:
        q_n += 1
        free_text[c].append(uid(13, q_n))
        add("question", ("uuid", "course_uuid", "body", "type", "default_points"),
            uid(13, q_n), uid(6, c), body, "free_text", 2.5)

    for qi in range(2 if c == 1 else 1):
        task_n += 1
        quiz_n += 1
        tu, qzu = uid(9, task_n), uid(15, quiz_n)
        opens = START + timedelta(weeks=6 + 5 * qi)
        add("task", ("uuid", "course_section_uuid", "name"), tu, sections[c][2 + qi % 2], f"Quiz {qi + 1}")
        add("quiz", ("uuid", "task_uuid", "title", "time_limit", "available_from", "available_until",
                     "attempts_allowed", "grading_method"),
            qzu, tu, f"Quiz {qi + 1}: {COURSES[c - 1][2][1 + qi]}", 30, opens, opens + timedelta(days=10), 2,
            GRADING_METHODS[(quiz_n - 1) % len(GRADING_METHODS)])
        used = questions[c][qi * 2:qi * 2 + 7]
        written = free_text[c][qi]
        for pos, (qu, *_) in enumerate(used, start=1):
            add("quiz_question", ("quiz_uuid", "question_uuid", "position", "points"), qzu, qu, pos, 2.5)
        add("quiz_question", ("quiz_uuid", "question_uuid", "position", "points"),
            qzu, written, len(used) + 1, 2.5)
        for m in enrolled[c]:
            if random.random() > 0.85:
                continue
            for attempt in range(2 if random.random() < 0.35 else 1):
                att_n += 1
                au = uid(16, att_n)
                started = opens + timedelta(days=random.uniform(0.2, 9.5) if attempt == 0 else random.uniform(5, 9.8))
                # A few attempts are still open when the snapshot is taken.
                in_progress = random.random() < 0.06
                add("quiz_attempt", ("uuid", "quiz_uuid", "student_uuid", "started_at", "submitted_at"),
                    au, qzu, users[m], started,
                    None if in_progress else started + timedelta(minutes=random.randint(8, 28)))
                add("quiz_answer_text", ("attempt_uuid", "question_uuid", "free_text"),
                    au, written, random.choice(FREE_TEXT_ANSWERS))
                # Free text is marked by hand, so some answers have no grade yet.
                if not in_progress and random.random() < 0.75:
                    grade_n += 1
                    add("grade", ("uuid", "grader_uuid", "submission_uuid", "attempt_uuid",
                                  "question_uuid", "points", "feedback", "graded_at"),
                        uid(12, grade_n), users[random.choice([PROFS[c - 1], HIWIS[c % 2]])],
                        None, au, written, round(2.5 * bell(0.7, 0.25) * 2) / 2,
                        random.choice(FEEDBACK), started + timedelta(days=random.randint(2, 9)))
                for qu, ous, difficulty, distractor in used:
                    p = min(0.95, difficulty + 0.2 * attempt)
                    fractions = [f for _, f in ous]
                    multi = max(fractions) < 1.0
                    best = [i for i, f in enumerate(fractions) if f > 0] if multi else [fractions.index(max(fractions))]
                    if random.random() < p:
                        picks = best
                    elif random.random() < 0.6:
                        picks = [distractor]
                    else:
                        picks = [random.choice([i for i in range(len(ous)) if i not in best])]
                    for i in sorted(set(picks)):
                        add("quiz_answer_option", ("attempt_uuid", "selected_option_uuid"), au, ous[i][0])

# forums
disc_n = post_n = 0
for c in range(1, 4):
    fo = uid(17, c)
    add("forum", ("uuid", "course_section_uuid", "title"), fo, sections[c][0], "Allgemeines Forum")
    people = enrolled[c] + [PROFS[c - 1], HIWIS[c % 2]]
    for topic in random.sample(TOPICS, 12):
        disc_n += 1
        du = uid(20, disc_n)
        t = activity_time(START, END - timedelta(days=3))
        post_n += 1
        root = uid(18, post_n)
        add("discussion", ("uuid", "forum_uuid", "root_post_uuid", "title", "created_at"), du, fo, root, topic, t)
        root_author = random.choice(enrolled[c])
        add("post", ("uuid", "discussion_uuid", "parent_uuid", "author_uuid", "body", "created_at"),
            root, du, None, users[root_author], random.choice(BODIES), t)
        for _ in range(random.randint(1, 6)):
            t = activity_time(t, min(END, t + timedelta(days=3)))
            author = random.choice(people) if random.random() < 0.8 else random.choice([PROFS[c - 1], HIWIS[c % 2]])
            post_n += 1
            add("post", ("uuid", "discussion_uuid", "parent_uuid", "author_uuid", "body", "created_at"),
                uid(18, post_n), du, root, users[author], random.choice(BODIES), t)
            notif_n += 1
            add("notification", ("uuid", "recipient_uuid", "type", "payload", "created_at", "read_at"),
                uid(19, notif_n), users[root_author], "post", f'{{"post_uuid": "{uid(18, post_n)}"}}',
                t, t + timedelta(hours=random.randint(1, 48)) if random.random() < 0.5 else None)

with OUT.open("w", encoding="utf-8") as f:
    f.write("-- Generated by gen_seed.py; regenerate instead of editing.\n"
            "-- Import once into a fresh migrated database, as one transaction.\n\n")
    # grade references quiz_answer_text, so it is written last.
    for table in [t for t in rows if t != "grade"] + ["grade"]:
        cols, values = rows[table]
        f.write(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n")
        f.write(",\n".join("  (" + ", ".join(sql(v) for v in vals) + ")" for vals in values))
        f.write(";\n\n")

print(f"{OUT.name}: " + ", ".join(f"{t.strip(chr(34))} {len(v)}" for t, (_, v) in rows.items()))
